# Generated by Django 3.0.5 on 2021-04-11 04:13

import DashBoardApp.models
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('summary', models.TextField(default='')),
                ('rating', models.FloatField()),
                ('name', models.TextField(default='')),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('APIType', models.IntegerField()),
                ('downloads', models.TextField()),
                ('useCount', models.IntegerField()),
                ('sampleUrl', models.URLField()),
                ('downloadUrl', models.URLField()),
                ('dateModified', models.DateTimeField()),
                ('remoteFeed', models.TextField()),
                ('numComments', models.IntegerField()),
                ('commentsUrl', models.URLField()),
                ('Tags', djongo.models.fields.ArrayField(model_container=DashBoardApp.models.TextFieldWrapper)),
                ('category', models.TextField()),
                ('protocols', models.TextField()),
                ('serviceEndpoint', models.URLField()),
                ('version', models.FloatField()),
                ('wsdl', models.URLField()),
                ('data_formats', models.TextField()),
                ('apigroups', models.TextField()),
                ('example', models.TextField()),
                ('clientInstall', models.BooleanField()),
                ('authentication', models.TextField()),
                ('ssl', models.BooleanField()),
                ('readonly', models.TextField()),
                ('VendorAPIKits', models.TextField()),
                ('CommunityAPIKits', models.TextField()),
                ('blog', models.URLField()),
                ('forum', models.URLField()),
                ('support', models.URLField()),
                ('accountReq', models.BooleanField()),
                ('commercial', models.TextField()),
                ('provider', models.URLField()),
                ('managedBy', models.TextField()),
                ('nonCommercial', models.TextField()),
                ('dataLicensing', models.TextField()),
                ('fees', models.TextField()),
                ('limits', models.TextField()),
                ('terms', models.URLField()),
                ('company', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mashup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('rating', models.FloatField()),
                ('name', models.TextField()),
                ('label', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('MashupType', models.TextField()),
                ('downloads', models.IntegerField()),
                ('useCount', models.IntegerField()),
                ('sampleUrl', models.URLField()),
                ('dateModified', models.DateTimeField()),
                ('numComments', models.IntegerField()),
                ('commentsUrl', models.URLField()),
                ('tags', djongo.models.fields.ArrayField(model_container=DashBoardApp.models.TextFieldWrapper)),
                ('APIs', djongo.models.fields.ArrayField(model_container=DashBoardApp.models.TextArrayFieldWrapper)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
