# Generated by Django 3.0.5 on 2021-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
